from rest_framework.urls import path


from team.views import (
    ListTeamView,
    TeamByNameView,
    TeamByIdView,
    CreateTeamView,
    UpdateTeamView,
    ListTeamPlayerView,
    TeamPlayerByNicknameView,
    TeamPlayerByTeamIdView,
    TeamPlayerByTeamView,
    CreateTeamPlayerView,
    UpdateTeamPlayerView,
    DeleteTeamPlayerView,
    ListTeamStatView,
    TeamStatsByTeamIdView,
    TeamStatsByTeamNameView,
    CreateTeamStatView,
    UpdateTeamStatView
)


urlpatterns = [
    path(
        'list/',
        ListTeamView.as_view(),
        name='list-team'
    ),
    path(
        'name/<str:name>',
        TeamByNameView.as_view(),
        name='team-by-name'
    ),
    path(
        'id/<int:id>',
        TeamByIdView.as_view(),
        name='team-by-id'
    ),
    path(
        'create/',
        CreateTeamView.as_view(),
        name='create-team'
    ),
    path(
        'update/<int:id>',
        UpdateTeamView.as_view(),
        name='update-team'
    ),
    path(
        'player/list/',
        ListTeamPlayerView.as_view(),
        name='list-team-player'
    ),
    path(
        'player/nickname/<str:nickname>',
        TeamPlayerByNicknameView.as_view(),
        name='team-player-by-nickname'
    ),
    path(
        'name/player/<str:name>',
        TeamPlayerByTeamView.as_view(),
        name='team-player-by-team-name'
    ),
    path(
        'id/player/<int:id>',
        TeamPlayerByTeamIdView.as_view(),
        name='team-player-by-team-id'
    ),
    path(
        'player/create/',
        CreateTeamPlayerView.as_view(),
        name='create-team-player'
    ),
    path(
        'player/update/<int:id>',
        UpdateTeamPlayerView.as_view(),
        name='update-team-player'
    ),
    path(
        'player/delete/<int:id>',
        DeleteTeamPlayerView.as_view(),
        name='delete-team-player'
    ),
    path(
        'stat/list/',
        ListTeamStatView.as_view(),
        name='list-team-stat'
    ),
    path(
        'stat/<int:id>',
        TeamStatsByTeamIdView.as_view(),
        name='team-stat-by-team-id'
    ),
    path(
        'name/stat/<str:name>',
        TeamStatsByTeamNameView.as_view(),
        name='team-stat-by-team-name'
    ),
    path(
        'stat/create/',
        CreateTeamStatView.as_view(),
        name='create-team-stat'
    ),
    path(
        'stat/update/<int:id>',
        UpdateTeamStatView.as_view(),
        name='update-team-stat'
    ),
]